#!/bin/bash
script="menuShift"
author_name="# Mirza Golam Abbas Shahneel"
version="# 1.0.5"
modified="# Modified_21012017_0152";
localPath='/usr/local'
resourcePath='/usr/local/src/ServiceShifting'

pwd > $localPath/src/menuScrptLoc

#No Colors
NC='\033[0m'			  # Text Reset/No Color
# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White
# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White
# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

while :
  do
    clear
    date '+%d/%m/%y'>time
    var_date_time=$(<time);
    #echo -e "\033[1m "
	echo -e "${White} ~----==============================-----~"
	echo -e "${White} |${BPurple}        Welcome to Shifting Menu       ${NC}${White}|"
	echo -e "${White} | \033[30m        Date: $var_date_time      ${White}          |"
	echo -e "${White} |----==============================-----|"
	echo -e "${White} | ${Red} [1] Pre-Shifting             ${White}        |"
	echo -e "${White} |---------------------------------------|"
	echo -e "${White} | ${Purple} [2] Shifting and Post jobs  ${White}         |"
	echo -e "${White} |---------------------------------------|"
	echo -e "${White} | ${Green} [h] Instructions           ${White}          |"
	echo -e "${White} |---------------------------------------|"
	echo -e "${White} | ${BBlack} [0] Exit/Stop             ${White}           |"
	echo -e "${White} ~----==============================-----~"
	echo -e ""
	echo -en "${Purple} Select the task [1 - 2]:\n 'h' for instructions:\n '0' to exit: \n ${NC}"
		read item
		case $item in
		
		1)
		cd /usr/local/src/
		rm -f preShifT
		wget http://149.20.186.19/downloads/shifT/preShifT >>/dev/null 2>&1
		chmod a+x preShifT
		./preShifT
		
		echo "Press enter to exit."
		read
		;;
		
		
		2)
		cd /usr/local/src/
		rm -f postShift
		wget http://149.20.186.19/downloads/shifT/postShift >>/dev/null 2>&1
		chmod a+x postShift
		./postShift

		echo "Press enter to exit."
		read
		;;	
		
		h )
			#Help - Manual
			clear;
			cd /usr/share/man/en/man1;
			rm -f manShift
			wget http://149.20.186.19/downloads/shifT/manShift >/dev/null 2>&1
			chmod a+x manShift
			man ./manShift
			rm -f manShift
		echo "Press enter to exit."
		read
		;;

		0) 
		menuScrptLoc=$(cat $localPath/src/menuScrptLoc);
		cd $menuScrptLoc
		rm -f menuShift preShifT shifT postShift;
		history -c
		exit 0 ;;
			  
			*) echo "Please select number at least one option"; read ;;

	   esac
done

